### ISSUE TITLE
Consider labeling output data with relevant security labels

### ISSUE THREAD

**Issue by jmandel** [microsoft/FHIR-Tools-for-Anonymization#11]
For background on how to apply these, see: https://www.hl7.org/fhir/security-labels.html#rsl

https://www.hl7.org/fhir/v3/ObservationValue/cs.html#v3-ObservationValue-ANONYED is a relevant tag that would make sense to assign to `Resource.meta.security`. 

This would allow us to indicate that the output data have been subject to anonymization. (Another relevant tag might be https://www.hl7.org/fhir/v3/ObservationValue/cs.html#v3-ObservationValue-REDACTED; all this might be good to control with configuration.)

**Comment by BoyaWu10** [comment]
Thanks @jmandel ! We've added security labels for output data with PR #35 .
