### ISSUE TITLE
Add extensions to the deindentified data to indicate which operations were performed during anonymization (redacted, shifted, etc.).

### ISSUE THREAD

**Issue by JohnTimm** [microsoft/FHIR-Tools-for-Anonymization#52]
Per my comment at DeyDays 2020, I think that having extensions on FHIR elements that were modified during the anonymization process could be useful.

**Comment by ranvijaykumar** [comment]
We have raised a change request in FHIR spec for this: https://jira.hl7.org/browse/FHIR-28407

**Comment by qiwjin** [comment]
close this issue for inactive, feel free to reopen.
