### ISSUE TITLE
Mark pseudonymized identifiers more visibly

### ISSUE THREAD

**Issue by noemide** [microsoft/FHIR-Tools-for-Anonymization#79]
I noticed that this library only replaces the Identifier.value. While some information indivating that this might not be a "real" value is in the security attribute of the resource, I do not think that is enough. While I agree with #52 , I also do not think simply adding an extension is enough either.
Both the security entry and the extension can be jusifiably ignored by recieving applications. Those applications would than go on to interpret the value as a "real" value. This might quickly become a problem, e.g. if trying to find corresponding objects in another, non-pseudonymized (or pseudonymized with a different system and therefore different pseudonyms) data source.
I believe one solution to this problem would be to create and add a modifier extension  (https://www.hl7.org/fhir/extensibility.html#modifierExtension) to the Identifier. Modifier extensions tell the recieving application that this Identifier might not be what it expects and even if the system does not recognize the extension, it now knows that "something is different about this Identifier".
Another solution (which i personally would prefer since modifier extensions tend to cause problems) would be to also change the system. The original system could be added in an extension. This would avoid confusion and also some issues e.g. with constraints that test the format of an identifier (e.g. in a profile which specifies an error if the identifier.value does not start with two letters followed by a colon.). It might also be useful to add a coding to identifier.type which expresses that this is now a pseudonym generated from an "original" identifier.
Since i did not find information on how to handle pseudonyms in the FHIR spec, this might also be a topic that should be discuessed on the FHIR chat in order to get community feedback.

**Comment by ranvijaykumar** [comment]
Thanks for your detailed suggestions.

The anonymizer behavior is driven by the config file. The sample config file redacts most of the the identifier.value and hashes Resource.id. If you want to redact, or hash the identifier.system, you can do so by adding a corresponding configuration. If you want to retain the existing id, you can do so by removing the corresponding configuraiton. However, we consider resource ids as PIIs, and hence recommend removing or hashing it. Ideally, the recipient of anonymized data should not be able to join this data with another set of data using Ids.

**Comment by noemide** [comment]
Thank you for your response. I agree with you on the subject of Resource id. 
However, I believe it woud be useful to have an option to simply relplace the Identifier.system with an also human-readable (not hashed) one. E.g. "example.org/PatID" -> "example.org/HashedPathId". I see that defining such an "alias" for a lot of Sytem-URLs might bloat the configuration file, but maybe there could be an extra file for that?

**Comment by ranvijaykumar** [comment]
You should be able to achieve that using the "substitute" method we released recently. See the documentation here: https://github.com/microsoft/FHIR-Tools-for-Anonymization#sample-rules-using-fhirpath

**Comment by noemide** [comment]
Thanks, that should work!
